 
version: '2'

services:

  phpfpm:
    image: matricali/phalcon:3.4-php7.3-stretch-fpm
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:latest
    links:
      - phpfpm
      - db
    volumes:
      - ./public:/var/www/html/public
      - ./nginx-virtualhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - ./db:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
