<div>

    <form action="">
        <label for="if_else">Si: </label>
 
    <select name="P1" id="if_else">

        <option><?php echo $if1 ?></option>
        <option><?php echo $if2 ?></option>
        <option><?php echo $if3 ?></option>
        
    </select>
    
    </form>

    <br>

    <form action="">
        
        <label for="Entonces">Entonces: </label>
        
        <select name="P2" id="Entonces">
            
            <option><?php echo $then1 ?></option>
            <option><?php echo $then2 ?></option>
            <option><?php echo $then3 ?></option>
            
        </select>
        
    </form>

    <br>

    <input type="submit">
</div>